Keep only external links checks
veggiemonk/awesome-docker pull request #911
Opened 2020-11-08 20:48 UTC by veggiemonk

fixes 908

2020-11-09 17:45 UTC, agebhar1 approved these changes
LGTM :+1:

2020-11-09 19:01 UTC, mash1t commented
@veggiemonk @agebhar1 

The last two commits contain the following changes:
- move tests to subfolder ./tests
- remove some not needed code in tests/pull_request.js
- add tests/all.js for running tests with GitHub token locally via `npm run test`
- move duplicate methods to helper.js

It would be great if you could give me feedback, especially on the naming of the files.

2020-11-09 19:16 UTC, agebhar1 requested changes

2020-11-09 19:16 UTC, agebhar1 commented on tests/pull_request.js
> +  console.log(`skipping GitHub repository check. Run "npm run test" to execute them manually.`);
the 'test' script was removed from package.json within this commit

2020-11-09 19:18 UTC, agebhar1 approved these changes
I'm fine with the changes :+1:

2020-11-10 08:20 UTC, veggiemonk commented
I'll have a look 😄

2020-11-11 07:47 UTC, veggiemonk commented
Thank you @mash1t and @agebhar1 

Nice work 😄

2020-11-11 07:48 UTC, merged