use latest version for GitHub Action(s)
veggiemonk/awesome-docker pull request #914
Opened 2020-11-18 13:15 UTC by agebhar1

> Run actions/setup-node@83c9f7a7df54d6b57455f7c57ac414f2ae5fb8de
>   Error: Unable to process command '::add-path::/opt/hostedtoolcache/node/12.19.0/x64/bin' successfully.
>   Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

2020-11-18 22:53 UTC, veggiemonk requested changes
Use git sha instead if you want to upgrade actions

2020-11-19 17:06 UTC, agebhar1 commented on .github/workflows/pull_request.yml
> +      - uses: actions/cache@v2
I updated to Git SHAs.

2020-11-20 07:25 UTC, veggiemonk approved these changes

2020-11-20 07:26 UTC, veggiemonk commented
Nice job! 👍 thanks 😄

2020-11-20 07:26 UTC, merged